In [1]:
#Create 2D numpy array using arange() function.
# 1st question
import numpy as np
new_arr = np.arange(9).reshape(3,3)
print(new_arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:
#Create 3D array from 1D numpy array.
# 2nd question
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
#Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
#3rd question
import numpy as np
x = np.arange(2, 11).reshape(3,3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
#Write a NumPy program to reverse an array (first element becomes last).
# 4th question
import numpy as np
x = np.arange(1, 5)
x = x[::-1]
print(x)

[4 3 2 1]


In [5]:
#Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
# 5th question
import numpy as np
x = np.ones((4,4))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [6]:
#Create a 2D array A with 4x4 size then split it into 3 different arrays B(1x4),C(2x4) and D(2x4).
# 6th question
a = np.random.randint(7,size=(4,4))
a


array([[2, 1, 5, 4],
       [0, 6, 3, 4],
       [1, 0, 0, 1],
       [2, 5, 2, 1]])

In [7]:
b=a[0:1]
b

array([[2, 1, 5, 4]])

In [8]:
c=a[0:2]
c

array([[2, 1, 5, 4],
       [0, 6, 3, 4]])

In [9]:
d=a[2:]
d

array([[1, 0, 0, 1],
       [2, 5, 2, 1]])

In [10]:
#Perform element wise multiplication of arrays C and D in question 6.
# 7th question
a1 = np.array([[2, 6, 1, 4],[0, 0, 4, 6]])
a2 = np.array([[1, 5, 3, 1],[6, 0, 5, 2]])
print(a1*a2)

[[ 2 30  3  4]
 [ 0  0 20 12]]


In [11]:
#Create a numpy array matrix of size 3x4. Find column which has highest sum and display.
# 8th question
a = np.random.randint(7,size=(3,4))
b =list(a.sum(axis=1))
print(a)
print("The highest sum column is {}".format(b.index(max(b))))

[[0 5 6 5]
 [6 0 3 5]
 [2 2 3 3]]
The highest sum column is 0
